export const legalParagraphs = [
  "Propósito y alcance",
  "Categorías de información",
  "Cata Club podrá gestionar, según la función utilizada:",
  "    • Identidad, contacto y cuenta: nombres, apellidos, documento identificativo cuando sea necesario, correo, teléfono, credenciales y relaciones de representación.",
  "    • Actividad deportiva y asistencia: alumno asociado, nivel o información deportiva, inscripción, horarios y asistencia.",
  "    • Pagos y comprobantes: estado de pago, importe, fecha, referencia y archivos o datos de comprobantes.",
  "    • Información médica o de emergencia: datos proporcionados para atender una situación deportiva o de emergencia.",
  "    • Perfil e imagen: fotografía de perfil y material de imagen cuando exista autorización o permiso aplicable.",
  "    • Información técnica y de auditoría: eventos de acceso, cambios, aceptación de versiones, cuenta, fecha y hora, y datos técnicos necesarios para seguridad y trazabilidad.",
  "Finalidades operativas",
  "La información puede utilizarse para crear y proteger cuentas, gestionar alumnos y representantes, coordinar actividades y asistencia, administrar pagos y comprobantes, atender emergencias, mantener la seguridad, responder consultas, documentar decisiones y demostrar qué versión de cada documento fue aceptada.",
  "No se propone utilizar la información para una finalidad incompatible con la comunicada sin revisión previa.",
  "Acceso y proveedores",
  "El acceso se limitará, a alto nivel, a la persona usuaria sobre su cuenta y alumnos asociados, representantes cuando corresponda, personal administrativo o deportivo con función pertinente y personas proveedoras que presten servicios tecnológicos u operativos bajo instrucciones de Cata Club. No se nombran proveedores no confirmados.",
  "Seguridad e incidentes",
  "Cata Club aplicará medidas administrativas y técnicas razonables para proteger la información, controlar accesos y mantener registros de actividad. Si se identifica un incidente que requiera comunicación, se evaluará y se informará mediante los canales disponibles, incluido cataclub.loja@proton.me.",
  "Conservación",
  "La información se conservará mientras sea necesaria para prestar el servicio, mantener la seguridad, atender solicitudes o cumplir obligaciones aplicables, según corresponda.",
  "Derechos, consultas y revocación",
  "Las consultas, solicitudes de acceso, corrección u otras peticiones relacionadas con la información se recibirán en cataclub.loja@proton.me y se gestionarán administrativamente.",
  "La persona puede solicitar retirar su autorización cuando la gestión se base en ella. El retiro opera hacia el futuro y puede limitar funciones que necesiten esa información. Retirar una autorización no equivale automáticamente a borrar datos: Cata Club debe distinguir la solicitud de eliminación de la conservación necesaria para operación, seguridad, auditoría o exigencias legales.",
  "Menores y representantes",
  "Aceptación, versiones y auditoría",
  "La interfaz debe mostrar una sola casilla inicialmente desmarcada y bloqueante:",
  "[ ] Acepto los Términos de uso, el Aviso de privacidad, el tratamiento de datos médicos y la difusión pública de imagen conforme al documento de Permiso público de difusión de imagen FETM.",
  "La aceptación agrupada debe auditar por separado cada documento o versión, timestamp, cuenta y representante cuando aplique. Las cuentas existentes deben aceptar al siguiente inicio de sesión; hasta entonces solo podrán revisar los documentos o cerrar sesión. Nunca se autoaceptará.",
] as const;
