"""add version_contrasenia to usuario

Revision ID: 84d1597c9f41
Revises: d3bc8c020e36
Create Date: 2026-07-22 08:22:23.731383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84d1597c9f41'
down_revision: Union[str, Sequence[str], None] = 'd3bc8c020e36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cierre_mensual_ranking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nivel_ranking_id', sa.Integer(), nullable=False),
    sa.Column('anio', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('personas_procesadas', sa.Integer(), nullable=False),
    sa.Column('cerrado_por_id', sa.Integer(), nullable=False),
    sa.Column('cerrado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cerrado_por_id'], ['persona.id'], ),
    sa.ForeignKeyConstraint(['nivel_ranking_id'], ['nivel_ranking.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('version_contrasenia', sa.Integer(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_column('version_contrasenia')

    op.drop_table('cierre_mensual_ranking')
    # ### end Alembic commands ###
